In [17]:
# speed test between list and the numpy in python 
# speed test in list python 
import numpy as np 
import time

size = 1000000
list1 = list(range(size))
list2 = list(range(size))
start = time.time()
add = [x+y for x,y in zip(list1,list2)]
end= time.time()

print("Time taken : ",end-start)

Time taken 0.08800363540649414


In [23]:
# speed test using numpy arrays
import numpy as np 
import time

size = 1000000
array1 = np.array(list(range(size)))
array2 = np.array(list(range(size)))

start = time.time()
result = array1+array2
end = time.time()

print("Time Taken", end - start)
# in conclusion the time taken by the numpy array is smaller than the list in python

Time Taken 0.004984378814697266


In [21]:
# to check the data size in both lists and arrays 
import sys
python_list = list(range(1000))
numpy_array = np.array(python_list)

print("size of python list:", sys.getsizeof(python_list)*len(python_list),"bytes")
print("size of numpy array:" , numpy_array.nbytes, "bytes")

size of python list 8056000 bytes
size of numpy array 4000 bytes


In [5]:
# creating the numpy array using diff functions
import numpy as np
array1 = np.array([[1,2,3],[4,5,6]])

In [7]:
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
array1.ndim

2

In [11]:
array1.shape

(2, 3)

In [13]:
array1.size

6

In [15]:
array1.dtype

dtype('int32')

In [19]:
# creating arrays using a simple function 
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.full((2,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [29]:
# changing the data type of the numpy arrays 
arr1= np.array([[1,2,3],[5,8,9],[23,352,5235]],dtype = 'float32')

In [32]:
arr1

array([[1.000e+00, 2.000e+00, 3.000e+00],
       [5.000e+00, 8.000e+00, 9.000e+00],
       [2.300e+01, 3.520e+02, 5.235e+03]], dtype=float32)

In [34]:
arr1.astype('int32') #conversion from float 32 to int 32

array([[   1,    2,    3],
       [   5,    8,    9],
       [  23,  352, 5235]])

In [40]:
# reshaping and flattening the array 
arr3 = np.array([[1,5,8],[4,5,6]])

In [42]:
arr3

array([[1, 5, 8],
       [4, 5, 6]])

In [44]:
arr3.reshape((3,2)) #it should be equal to the no of elements 

array([[1, 5],
       [8, 4],
       [5, 6]])

In [46]:
arr3.flatten() #makes the array 1d from nd 

array([1, 5, 8, 4, 5, 6])

In [54]:
  # multidimensional indexing and slicing in array 
array4 = np.array([
    [[12,124,1512],
     [231,2612,1251]],
    
    [[215,125125,1623],
     [2323,87,923]]
])


In [56]:
array4

array([[[    12,    124,   1512],
        [   231,   2612,   1251]],

       [[   215, 125125,   1623],
        [  2323,     87,    923]]])

In [62]:
array4[:,0,:]

array([[    12,    124,   1512],
       [   215, 125125,   1623]])